#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_fmod = env_modules.Clone()

fmod_lib = "fmod"
fmodstudio_lib = "fmodstudio"

# Use logging versions in the editor and in debug templates
if env["target"] in ["editor", "template_debug"]:
    fmod_lib += "L"
    fmodstudio_lib += "L"

# Linux
if env["platform"] == "linuxbsd":
    env.Append(LIBS=['lib%s' % fmod_lib, 'lib%s' % fmodstudio_lib])
    if env["arch"] == "arm32":
        env.Append(LIBPATH=[Dir("lib/arm").abspath])
    elif env["arch"] == "arm64":
        env.Append(LIBPATH=[Dir("lib/arm64").abspath])
    elif env["arch"] == "x86_32":
        env.Append(LIBPATH=[Dir("lib/x86").abspath])
    elif env["arch"] == "x86_64":
        env.Append(LIBPATH=[Dir("lib/x86_64").abspath])

# macOS
elif env["platform"] == "macos":
    env.Append(LIBS=['lib%s' % fmod_lib, 'lib%s' % fmodstudio_lib])
    env.Append(LIBPATH=[Dir("lib/macos").abspath])

# Windows
elif env["platform"] == "windows":
    # TODO: mingw?
    env.Append(LIBS=['%s_vc.lib' % fmod_lib, '%s_vc.lib' % fmodstudio_lib])
    if env["arch"] == "x86_32":
        env.Append(LIBPATH=[Dir("lib/x86").abspath])
    elif env["arch"] == "x86_64":
        env.Append(LIBPATH=[Dir("lib/x86_64").abspath])

# Sources
env_fmod.add_source_files(env.modules_sources, "*.cpp")

